using Transaction.Domain.Entities;
using Transaction.Domain.Transactions;

namespace Transaction.Application.Transactions;

/// <summary>Transaction just recorded.</summary>
/// <param name="Id">Identifier generated by the server.</param>
/// <param name="Type">Kind of entry: <c>Debit</c> or <c>Credit</c>.</param>
/// <param name="AccountId">Account the entry belongs to.</param>
/// <param name="Amount">Recorded value.</param>
/// <param name="CreatedBy">Who recorded the entry, trimmed.</param>
/// <param name="CreatedAt">Server time of the recording, in UTC.</param>
public sealed record CreateTransactionResponse(
    Guid Id,
    TransactionType Type,
    int AccountId,
    decimal Amount,
    string CreatedBy,
    DateTimeOffset CreatedAt)
{
    internal static CreateTransactionResponse From(RawTransaction transaction) => new(
        transaction.Id, transaction.Type, transaction.AccountId,
        transaction.Amount, transaction.CreatedBy, transaction.CreatedAt);
}
