// <auto-generated />
using System;
using BalanceProjection.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BalanceProjection.Infrastructure.Migrations
{
    [DbContext(typeof(BalanceProjectionDbContext))]
    partial class BalanceProjectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BalanceProjection.Domain.Entities.AccountBalance", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("LastTransactionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCredits")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalDebits")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("TransactionCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId");

                    b.ToTable("AccountBalances", "balance_projection");
                });

            modelBuilder.Entity("BalanceProjection.Domain.Entities.BusinessAck", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RawTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionId");

                    b.HasIndex("ProcessedAt")
                        .HasFilter("\"PublishedAt\" IS NULL");

                    b.ToTable("BusinessAcks", "balance_projection");
                });

            modelBuilder.Entity("BalanceProjection.Domain.Entities.ProcessedTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RawTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionId");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("RawTransactionId")
                        .IsUnique();

                    b.ToTable("ProcessedTransactions", "balance_projection");
                });
#pragma warning restore 612, 618
        }
    }
}
